from pySMOKEPostProcessor import PostProcessor, script_utils
import xml.etree.ElementTree as ET # It is required for what I have in mind. Maybe we move this to CXX_Wrapper and save the variable from there.
import os   # Required for ET, if removed take this out as well
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.integrate import cumulative_trapezoid

class CumulativeDeposition:
    """
    Parameters
    ----------
    kineticFolder : string
                Pointer to the folder containing the kinetics.surface.xml and surface_reaction_names.xml files
    outputFolder:   string
                Pointer to the folder containing the Output.xml file

    allCarbon:      bool
                Decide if deposition is evaluated on all bulk species or on C(B) only.
                TODO: at the moment, only the False option is available

    """
    def __init__(self,
                kineticFolder: str,
                outputFolder: str,
                class_group_file: str,
                allCarbon: bool = False,
                sort_type = [['reactiontype']],
                carbon_density: float = 2000.,
                area: float = None):

        self.kineticFolder = kineticFolder
        self.outputFolder = outputFolder

        self.bulk_density = carbon_density  # Carbon density [kg/m3]
        self.MW = 12.01     # Carbon MW [kg/kmol]
        self.area = area    # Hp constant area, will be eventually read from Output.xml when variable
        if self.area is not None:
            self.iExtensiveEnabled = True
        else:
            self.iExtensiveEnabled = False

        targets = ['C(B)']
        self.allCarbon = allCarbon
        if allCarbon:
            targets.append('c(B)')  # Non mi piace nemmeno hardcoded, va fatto meglio
        self.targets = targets
        self.sort_type = sort_type    # Default classification option
        rxns_sorted = script_utils.get_sortedrxns(kineticFolder, class_group_file, heterogeneous_reactions=True)
        self.rxns_sorted = rxns_sorted

    def setClassification(self, sort_type):
        self.sort_type = sort_type
    
    def plotCumulativeDeposition(self,
                    profilesTag: str = 'profiles',
                    lump_steps: int = 1,
                    units: str = "mass-specific",
                    threshold: float = 0.01,
                    fig: plt.Figure = None,
                    ax: plt.Axes = None):
        
        """
        Parameters
        ----------
            profileTag: string 
                Name of the tag to look for in the Output.xml file. Standard is 'profiles'.
            lump_steps: int
                If different from 1, reduces the number of steps used for integral ROPA evaluation, Nsteps = N/lump_steps
            units: str
                Units used as y-axis in the plot. Alternatives: 'mass-specific', 'moles-specific', 'mass', 'moles', 'thickness'
                For extensive units (e.g. mass), it is required to also set the area in the class constructor.
            threshold: float
                Threshold for filtering reaction classes to plot. Only classes whose maximum contribution is above the (relative) threshold are plotted.
            fig,ax: matplotlib.pyplot objects
                If not provided, they are created by the function. Intended for subplots usage.
        
        Returns
        -------
        figure,axis (matplotlib.pyplot objects) for the figure generated by the function
        """
        # The tag argument is only useful for phases where it has a different name (Riccardo...)
        timesteps = self.getTimeProfile(tag=profilesTag)

        df_ROPAt = []
        for i in range(int(len(timesteps)/lump_steps)): # è stra lento nel chiamare Ny volte la funzione perché re-inizializza tutto ad ogni iter;
                            # o si riscrive da capo o si trova un workaround
            i_lump = i*lump_steps
            df = script_utils.process_classes(
                    simul_fld=self.outputFolder,kin_xml_fld=self.kineticFolder, rxns_sorted_obj=self.rxns_sorted,
                    species_list=self.targets,  sortlists=self.sort_type,       heterogeneous_reactions=True,
                    ropa_type='local',          local_value=timesteps[i_lump],       weigh='false')
            if isinstance(df, list):
                for d in df:
                    d["time"] = timesteps[i_lump]
                df_ROPAt.extend(df)
            else:
                df["time"] = timesteps[i_lump]
                df_ROPAt.append(df)
        if self.allCarbon:
            collapsed = []
            for df in df_ROPAt:
                s = df.fillna(0).sum(axis=0)
                s["time"] = df["time"].iloc[0]
                collapsed.append(s)
            df_ROPAt = pd.DataFrame(collapsed)
        df_ROPAt = df_ROPAt.fillna(0)
        self.ROPAbyClass_t = df_ROPAt
        df_ROPAintegral = self.getROPAIntegralTimeHistory(df_ROPAt)
        df_ROPAintegral = self.convertToDesiredUnits(data = df_ROPAintegral, units = units)
        ylab = self.getLabelFromUnits(units)

        cols_unfiltered = [c for c in df_ROPAintegral.columns if c != "time"]
        total_deposition = df_ROPAintegral[cols_unfiltered].sum(axis=1)
        cols = [col for col in cols_unfiltered if (abs(df_ROPAintegral[col].max()) > threshold*total_deposition.max())]

        if fig is None or ax is None:
            fig,ax = plt.subplots(figsize=(7.,6.))
        ax.stackplot( df_ROPAintegral["time"], *[df_ROPAintegral[col] for col in cols], labels=[col for col in cols], alpha=0.87,
                     edgecolor = 'k', linewidth = 0.6 )
        fontsz = 14
        ax.set_xlim(left=0,right=df_ROPAintegral['time'].values[-1])
        ax.set_xlabel("Time [s]",fontsize=fontsz)
        ax.set_ylabel(ylabel=ylab,fontsize=fontsz)
        ax.set_title("Cumulative deposition by reaction class",fontsize=fontsz+2)
        ax.grid(True,alpha=0.2)
        ax.legend(fontsize=fontsz)
        fig.tight_layout()
        return fig,ax


    def getTimeProfile(self,tag='profiles'):
        
        output_root = ET.parse(os.path.join(self.outputFolder, "Output.xml")).getroot()
        node = output_root.find(tag)
        
        if node is None or node.text is None:
            raise ValueError(f"Tag '{tag}' not found or empty in the XML.")
        
        timesteps = np.fromiter( (float(line.split()[0]) for line in node.text.strip().splitlines() if line.strip()), dtype=float )
        return timesteps

    def getROPAIntegralTimeHistory(self, df_ROPAt):

        if "time" not in df_ROPAt.columns:
            raise ValueError("Column 'time' not found")

        time = df_ROPAt["time"].unique()
        Nt = len(time)

        cols = df_ROPAt.select_dtypes(include=[np.number]).columns.tolist()
        cols.remove("time")

        n_rows = len(df_ROPAt) // Nt
        data = df_ROPAt[cols].to_numpy().reshape(Nt, n_rows, len(cols))

        integ = cumulative_trapezoid(y=data, x=time, axis=0, initial=0)

        df_integrated = df_ROPAt.copy()
        df_integrated[cols] = integ.reshape(len(df_ROPAt), len(cols))

        return df_integrated
    
    def convertToDesiredUnits(self, data:pd.DataFrame, units:str):
        # TODO: Add specific-volumetric quantities (for soot comparison)
        if not self.iExtensiveEnabled:
            if units == 'mass' or units == 'moles':
                raise ValueError("Error! Extensive units require area as input!")
        cols = [c for c in data.columns if c != "time"]
        match units:
            case 'mass-specific':
                data[cols] *= self.MW
                return data
            case 'moles':
                data[cols] *= self.area
            case 'mass':
                data[cols] *= self.area * self.MW
            case 'mass-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'moles-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'thickness':
                data[cols] *= self.MW/self.bulk_density * 1.E6
            case 'moles-specific':
                dummy = True
            case _:
                raise ValueError("Units not recognised. Options available: 'mass-specific', 'moles-specific', 'mass', 'moles', 'thickness' ")

        return data

    @staticmethod
    def getLabelFromUnits(units):
        ylab = "Carbon "
        match units:
            case 'mass-specific':
                ylab += '[kg/m2]'
            case 'moles-specific':
                dummy = True
            case 'moles':
                ylab += '[kmol]'
            case 'mass':
                ylab += '[kg]'
            case 'mass-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'moles-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'thickness':
                ylab += r'[$\mu$m]'
            case _:
                raise ValueError("Units not recognised")
        return ylab