from pySMOKEPostProcessor.surfacereactions_utilities.time_history_utilities import getTimeProfile, getROPAIntegralTimeHistory
from pySMOKEPostProcessor import script_utils
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


# These two classes do very similar things. Ideally they can be restructured as a parent + 2 children classes or even a single one with more inputs.
class CumulativeDeposition:
    """
    Parameters
    ----------
    kineticFolder : string
                Pointer to the folder containing the kinetics.surface.xml and surface_reaction_names.xml files
    outputFolder:   string
                Pointer to the folder containing the Output.xml file

    allCarbon:      bool
                Decide if deposition is evaluated on all bulk species or on C(B) only.
                TODO: at the moment, only the False option is available

    """
    def __init__(self,
                kineticFolder: str,
                outputFolder: str,
                class_group_file: str,
                allCarbon: bool = False,
                sort_type = [['reactiontype']],
                carbon_density: float = 2000.,
                area: float = None):

        self.kineticFolder = kineticFolder
        self.outputFolder = outputFolder

        self.bulk_density = carbon_density  # Carbon density [kg/m3]
        self.MW = 12.01     # Carbon MW [kg/kmol]
        self.area = area    # Hp constant area, will be eventually read from Output.xml when variable
        if self.area is not None:
            self.iExtensiveEnabled = True
        else:
            self.iExtensiveEnabled = False

        targets = ['C(B)']
        self.allCarbon = allCarbon
        if allCarbon:
            targets.append('c(B)')  # Non mi piace nemmeno hardcoded, va fatto meglio
        self.targets = targets
        self.sort_type = sort_type    # Default classification option
        rxns_sorted = script_utils.get_sortedrxns(kineticFolder, class_group_file, heterogeneous_reactions=True)
        self.rxns_sorted = rxns_sorted

    def setClassification(self, sort_type):
        self.sort_type = sort_type
    
    def plotCumulativeDeposition(self,
                    profilesTag: str = 'profiles',
                    lump_steps: int = 1,
                    units: str = "mass-specific",
                    threshold: float = 0.01,
                    fig: plt.Figure = None,
                    ax: plt.Axes = None,
                    colors = sns.color_palette("muted") ):
        
        """
        Parameters
        ----------
            profileTag: string 
                Name of the tag to look for in the Output.xml file. Standard is 'profiles'.
            lump_steps: int
                If different from 1, reduces the number of steps used for integral ROPA evaluation, Nsteps = N/lump_steps
            units: str
                Units used as y-axis in the plot. Alternatives: 'mass-specific', 'moles-specific', 'mass', 'moles', 'thickness'
                For extensive units (e.g. mass), it is required to also set the area in the class constructor.
            threshold: float
                Threshold for filtering reaction classes to plot. Only classes whose maximum contribution is above the (relative) threshold are plotted.
            fig,ax: matplotlib.pyplot objects
                If not provided, they are created by the function. Intended for subplots usage.
        
        Returns
        -------
        figure,axis (matplotlib.pyplot objects) for the figure generated by the function
        """
        # The tag argument is only useful for phases where it has a different name (Riccardo...)
        timesteps = getTimeProfile(outputFolder=self.outputFolder, tag=profilesTag)

        df_ROPAt = []
        for i in range(int(len(timesteps)/lump_steps)): # è stra lento nel chiamare Ny volte la funzione perché re-inizializza tutto ad ogni iter;
                            # o si riscrive da capo o si trova un workaround
            i_lump = i*lump_steps
            df = script_utils.process_classes(
                    simul_fld=self.outputFolder,kin_xml_fld=self.kineticFolder, rxns_sorted_obj=self.rxns_sorted,
                    species_list=self.targets,  sortlists=self.sort_type,       heterogeneous_reactions=True,
                    ropa_type='local',          local_value=timesteps[i_lump],       weigh='false')
            if isinstance(df, list):
                for d in df:
                    d["time"] = timesteps[i_lump]
                df_ROPAt.extend(df)
            else:
                df["time"] = timesteps[i_lump]
                df_ROPAt.append(df)
        if self.allCarbon:
            collapsed = []
            for df in df_ROPAt:
                s = df.fillna(0).sum(axis=0)
                s["time"] = df["time"].iloc[0]
                collapsed.append(s)
            df_ROPAt = pd.DataFrame(collapsed)
        else:
            df_ROPAt = pd.concat(df_ROPAt, ignore_index=True)
        df_ROPAt = df_ROPAt.fillna(0)
        self.ROPAbyClass_t = df_ROPAt
        df_ROPAintegral = getROPAIntegralTimeHistory(df_ROPAt)
        df_ROPAintegral = self.convertToDesiredUnits(data = df_ROPAintegral, units = units)
        ylab = self.getLabelFromUnits(units)

        cols_unfiltered = [c for c in df_ROPAintegral.columns if c != "time"]
        total_deposition = df_ROPAintegral[cols_unfiltered].sum(axis=1)
        cols = [col for col in cols_unfiltered if (abs(df_ROPAintegral[col].max()) > threshold*total_deposition.max())]

        if fig is None or ax is None:
            fig,ax = plt.subplots(figsize=(7.,6.))
        ax.stackplot( df_ROPAintegral["time"], *[df_ROPAintegral[col] for col in cols], labels=[col for col in cols], 
                    alpha=0.87, edgecolor = 'k', linewidth = 0.6, colors = colors[:len(cols)] )
        fontsz = 14
        ax.set_xlim(left=0,right=df_ROPAintegral['time'].values[-1])
        ax.set_xlabel("Time [s]",fontsize=fontsz)
        ax.set_ylabel(ylabel=ylab,fontsize=fontsz)
        #ax.set_title("Cumulative deposition by reaction class",fontsize=fontsz+2)
        ax.grid(True,alpha=0.2)
        ax.legend(fontsize=fontsz,loc='center left', bbox_to_anchor=(1, 0.5))
        fig.tight_layout()
        return fig,ax
    
    def convertToDesiredUnits(self, data:pd.DataFrame, units:str):
        # TODO: Add specific-volumetric quantities (for soot comparison)
        if not self.iExtensiveEnabled:
            if units == 'mass' or units == 'moles':
                raise ValueError("Error! Extensive units require area as input!")
        cols = [c for c in data.columns if c != "time"]
        match units:
            case 'mass-specific':
                data[cols] *= self.MW
                return data
            case 'moles':
                data[cols] *= self.area
            case 'mass':
                data[cols] *= self.area * self.MW
            case 'mass-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'moles-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'thickness':
                data[cols] *= self.MW/self.bulk_density * 1.E6
            case 'moles-specific':
                dummy = True
            case _:
                raise ValueError("Units not recognised. Options available: 'mass-specific', 'moles-specific', 'mass', 'moles', 'thickness' ")

        return data

    @staticmethod
    def getLabelFromUnits(units):
        ylab = "Deposited carbon "
        match units:
            case 'mass-specific':
                ylab += '[kg/m2]'
            case 'moles-specific':
                dummy = True
            case 'moles':
                ylab += '[kmol]'
            case 'mass':
                ylab += '[kg]'
            case 'mass-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'moles-specific-volumetric':
                raise ValueError("'specific-volumetric' units not implemented yet!")
            case 'thickness':
                ylab += r'[$\mu$m]'
            case _:
                raise ValueError("Units not recognised")
        return ylab


class CumulativeSootProduction: # We need a better way to handle soot species names, especially for newer models with liq,agg,pp, etc.
    def __init__(self,
            kineticFolder: str,
            outputFolder: str,
            class_group_file: str,
            soot_species: list[str] = ["BIN5AJ", "BIN5BJ", "BIN5CJ", "BIN6AJ", "BIN6BJ", "BIN6CJ", "BIN7AJ", "BIN7BJ", "BIN7CJ", "BIN8AJ", "BIN8BJ", "BIN8CJ", "BIN9AJ", "BIN9BJ", "BIN9CJ", "BIN10AJ", "BIN10BJ", "BIN10CJ", "BIN11AJ", "BIN11BJ", "BIN11CJ", "BIN12AJ", "BIN12BJ", "BIN12CJ", "BIN13AJ", "BIN13BJ", "BIN13CJ", "BIN14AJ", "BIN14BJ", "BIN14CJ", "BIN15AJ", "BIN15BJ", "BIN15CJ", "BIN16AJ", "BIN16BJ", "BIN16CJ", "BIN17AJ", "BIN17BJ", "BIN17CJ", "BIN18AJ", "BIN18BJ", "BIN18CJ", "BIN19AJ", "BIN19BJ", "BIN19CJ", "BIN20AJ", "BIN20BJ", "BIN20CJ", "BIN21AJ", "BIN21BJ", "BIN21CJ", "BIN22AJ", "BIN22BJ", "BIN22CJ", "BIN23AJ", "BIN23BJ", "BIN23CJ", "BIN24AJ", "BIN24BJ", "BIN24CJ", "BIN25AJ", "BIN25BJ", "BIN25CJ"],
            sort_type = [['reactiontype']],
            volume: float = None,
            ):

        self.kineticFolder = kineticFolder
        self.outputFolder = outputFolder

        self.volume = volume   # Hopefully constant.
        if self.volume is not None:
            self.iExtensiveEnabled = True
        else:
            self.iExtensiveEnabled = False

        self.targets = soot_species
        self.sort_type = sort_type
        rxns_sorted = script_utils.get_sortedrxns(kineticFolder, class_group_file, heterogeneous_reactions=False)
        self.rxns_sorted = rxns_sorted

    def setClassification(self, sort_type):
        self.sort_type = sort_type

    def plotSootProduction(self,
                    profilesTag: str = 'profiles',
                    lump_steps: int = 1,
                    units: str = "mass-specific",
                    threshold: float = 0.01,
                    fig: plt.Figure = None,
                    ax: plt.Axes = None,
                    colors = sns.color_palette("muted") ):
        """
        Parameters
        ----------
            profileTag: string 
                Name of the tag to look for in the Output.xml file. Standard is 'profiles'.
            lump_steps: int
                If different from 1, reduces the number of steps used for integral ROPA evaluation, Nsteps = N/lump_steps
            units: str
                Units used as y-axis in the plot. Alternatives: 'mass-specific', 'moles-specific', 'mass', 'moles', 'thickness'
                For extensive units (e.g. mass), it is required to also set the area in the class constructor.
            threshold: float
                Threshold for filtering reaction classes to plot. Only classes whose maximum contribution is above the (relative) threshold are plotted.
            fig,ax: matplotlib.pyplot objects
                If not provided, they are created by the function. Intended for subplots usage.
        
        Returns
        -------
        figure,axis (matplotlib.pyplot objects) for the figure generated by the function
        """
        # The tag argument is only useful for phases where it has a different name (Riccardo...)
        timesteps = getTimeProfile(outputFolder=self.outputFolder, tag=profilesTag)

        df_ROPAt = []
        for i in range(int(len(timesteps)/lump_steps)): # è stra lento nel chiamare Ny volte la funzione perché re-inizializza tutto ad ogni iter;
                            # o si riscrive da capo o si trova un workaround
            i_lump = i*lump_steps
            df = script_utils.process_classes(
                    simul_fld=self.outputFolder,kin_xml_fld=self.kineticFolder, rxns_sorted_obj=self.rxns_sorted,
                    species_list=self.targets,  sortlists=self.sort_type,       heterogeneous_reactions=False,
                    ropa_type='local',          local_value=timesteps[i_lump],  weigh='false', mass_ropa=True)
            if isinstance(df, list):
                for d in df:
                    d["time"] = timesteps[i_lump]
                df_ROPAt.extend(df)
            else:
                df["time"] = timesteps[i_lump]
                df_ROPAt.append(df)
        collapsed = []
        for df in df_ROPAt:
            s = df.fillna(0).sum(axis=0)
            s["time"] = df["time"].iloc[0]
            collapsed.append(s)
        df_ROPAt = pd.DataFrame(collapsed)
        df_ROPAt = df_ROPAt.fillna(0)
        self.ROPAbyClass_t = df_ROPAt
        df_ROPAintegral = getROPAIntegralTimeHistory(df_ROPAt)
        df_ROPAintegral = self.convertToDesiredUnits(data = df_ROPAintegral, units = units)
        ylab = self.getLabelFromUnits(units)

        cols_unfiltered = [c for c in df_ROPAintegral.columns if c != "time"]
        total_deposition = df_ROPAintegral[cols_unfiltered].sum(axis=1)
        cols = [col for col in cols_unfiltered if (abs(df_ROPAintegral[col].max()) > threshold*total_deposition.max())]

        if fig is None or ax is None:
            fig,ax = plt.subplots(figsize=(7.,6.))
        ax.stackplot( df_ROPAintegral["time"], *[df_ROPAintegral[col] for col in cols],  alpha = 0.87,
                    labels = [col for col in cols], edgecolor = 'k', linewidth = 0.6, colors = colors[:len(cols)] )

        fontsz = 14
        ax.set_xlim(left=0,right=df_ROPAintegral['time'].values[-1])
        ax.set_xlabel("Time [s]",fontsize=fontsz)
        ax.set_ylabel(ylabel=ylab,fontsize=fontsz)
        #ax.set_title("Cumulative deposition by reaction class",fontsize=fontsz+2)
        ax.grid(True,alpha=0.2)
        ax.legend(fontsize=fontsz,loc='center left', bbox_to_anchor=(1, 0.5))
        fig.tight_layout()
        return fig,ax
    
    def convertToDesiredUnits(self, data:pd.DataFrame, units:str):
        if not self.iExtensiveEnabled:
            if units == 'mass':
                raise ValueError("Error! Extensive units require volume as input!")
        cols = [c for c in data.columns if c != "time"]
        match units:
            case 'mass-specific':
                dummy = True
            case 'mass':
                data[cols] *= self.volume
            case _:
                raise ValueError("Units not recognised. Options available: 'mass-specific', 'mass'")
        return data
    
    @staticmethod
    def getLabelFromUnits(units):
        ylab = "Soot "
        match units:
            case 'mass-specific':
                ylab += '[kg/m3]'
            case 'mass':
                ylab += '[kg]'
            case _:
                raise ValueError("Units not recognised")
        return ylab